// <auto-generated />
using System;
using EfPlatzi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfPlatzi.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20230824174042_BulkInsertInitialData")]
    partial class BulkInsertInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EfPlatzi.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_category_id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dbd467ca-5628-40ec-99a1-8bd95fc78c1e"),
                            Description = "Actividades pendientes",
                            Name = "Actividades pendientes",
                            Weight = 20
                        },
                        new
                        {
                            Id = new Guid("4d762b80-b91b-4234-b600-ff67d9a9cc04"),
                            Description = "Actividades personales",
                            Name = "Actividades personales",
                            Weight = 50
                        });
                });

            modelBuilder.Entity("EfPlatzi.Models.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_task_id");

                    b.HasIndex("CategoryId");

                    b.ToTable("tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dbd467ca-5628-40ec-99a1-8bd95fc78c10"),
                            CategoryId = new Guid("dbd467ca-5628-40ec-99a1-8bd95fc78c1e"),
                            CreatedDate = new DateTime(2023, 8, 24, 11, 40, 42, 128, DateTimeKind.Local).AddTicks(210),
                            Description = "Pago de servicios publicos",
                            Priority = 1,
                            Title = "Pago de servicios publicos"
                        },
                        new
                        {
                            Id = new Guid("dbd467ca-5628-40ec-99a1-8bd95fc78c11"),
                            CategoryId = new Guid("4d762b80-b91b-4234-b600-ff67d9a9cc04"),
                            CreatedDate = new DateTime(2023, 8, 24, 11, 40, 42, 128, DateTimeKind.Local).AddTicks(222),
                            Priority = 2,
                            Title = "Terminar el proyecto de api"
                        });
                });

            modelBuilder.Entity("EfPlatzi.Models.Task", b =>
                {
                    b.HasOne("EfPlatzi.Models.Category", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EfPlatzi.Models.Category", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
